version: "3.8"

# --- Container간 통신 ---
networks:
  seol_net:
    driver: bridge

services:
  # --- ElasticSearch ---
  # https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - seol_net

  # --- Logstash ---
  # https://www.elastic.co/guide/en/logstash/7.11/docker-config.html
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.1
    container_name: logstash
    ports:
      - "5044:5044"
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - seol_net

  # --- Kibana ---
  # https://www.elastic.co/guide/en/kibana/7.11/docker.html
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - seol_net

  # --- Filebeat ---
  # https://www.elastic.co/guide/en/beats/filebeat/7.11/running-on-docker.html
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.11.1
    container_name: filebeat
    volumes:
      - ./elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log:ro  # 호스트의 로그 디렉토리를 마운트
    depends_on:
      - logstash
    networks:
      - seol_net


  # --- Fluentd ---
  fluentd:
    image: fluent/fluentd:v0.12.16
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./elk/fluent.conf:/fluentd/etc/fluent.conf
      - /var/log:/var/log:ro  # 호스트의 로그 디렉토리를 마운트
    depends_on:
      - elasticsearch
    networks:
      - seol_net
    

  # --- mysql ---
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # 루트 사용자 비밀번호
      MYSQL_DATABASE: seol # 생성할 기본 DB 이름
      MYSQL_USER: user # 추가할 사용자
      MYSQL_PASSWORD: user # 사용자 비밀번호
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - seol_net

volumes:
  mysql-data:
